FROM ninai/netgard:latest
LABEL maintainer "Edgar Y. Walker <edgar.walker@gmail.com>"

ADD . /src/v1_likelihood
RUN pip install -e /src/v1_likelihood
RUN pip install h5py

WORKDIR /src/v1_likelihood/scripts

ENTRYPOINT ["python3"]
